### PR TITLE
Add device dump for H110i

### PR DESCRIPTION
**Pull request by Lazzu**
## Proposed changes

I happened to have this device and decided to make a dump. Nothing else in the PR.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/audiohacked/OpenCorsairLink/blob/testing/CONTRIBUTING.md) doc
- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **testing branch** (left side). Also you should start *your branch* off *our testing*.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Check the commit's or even all commits' message styles matches our requested structure.

### CODE REVIEW

**Comment by audiohacked** [comment]
The device dump you have provided isn't the H110i.

**Comment by Lazzu** [comment]
It's not? What is it then? This cooler is the only Corsair product plugged in to my PC.

**Comment by naasi1** [comment]
Hi, great what you did! Would love to test that on my hackintosh. Is there a step by step giude what to enter in the terminal to connect to my H115i Pro? I've managed to install libusb and pkg-config but failed with the command "$ sudo ./OpenCorsairLink.elf". I just copied it exactly like that, do I need to customize it to make it work?
Sorry for this stupid question but I am totally new to that.

**Comment by audiohacked** [comment]
Line #11 lists the device as “Link Cooling Node”

**Comment by Lazzu** [comment]
Yes, and again the cooler is the only Corsair product plugged in to my system.
```$ lsusb
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 003: ID 0451:8440 Texas Instruments, Inc. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 1b1c:0c04 Corsair Link Cooling Node
Bus 001 Device 018: ID 0451:82ee Texas Instruments, Inc. 
Bus 001 Device 017: ID 0451:82ff Texas Instruments, Inc. 
Bus 001 Device 016: ID 046d:c318 Logitech, Inc. Illuminated Keyboard
Bus 001 Device 015: ID 046d:c332 Logitech, Inc. G502 Proteus Spectrum Optical Mouse
Bus 001 Device 014: ID 0451:8442 Texas Instruments, Inc. 
Bus 001 Device 002: ID 17cc:1420 Native Instruments 
Bus 001 Device 013: ID 04e8:3469 Samsung Electronics Co., Ltd 
Bus 001 Device 010: ID 0b05:1867 ASUSTek Computer, Inc. 
Bus 001 Device 008: ID 0b05:185c ASUSTek Computer, Inc. 
Bus 001 Device 006: ID 0b05:17cb ASUSTek Computer, Inc. Broadcom BCM20702A0 Bluetooth
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub```
I assume it reports the name wrongly or something else.

**Pull request merged**
