### PR TITLE
hid h110i extreme: fix number of fan/pump devices

### PR DESCRIPTION
**Pull request by malakudi**
HID device H110i Extreme (device id 0x42) has 2 fans and one pump. Fans with id > 2 report again fan with id 0. This fixes this.
Output before fix:
./OpenCorsairLink.elf --device 0
Dev=0, CorsairLink Device Found: H110i Extreme!

Vendor: Corsair
Product: H110i Extreme
Firmware: 32.0.0.0
Temperature 0: 24.63
Temperature 1: 24.63
Temperature 2: 24.63
Fan Speed 0: 581
Fan Speed 1: 957
Fan Speed 2: 2373
Fan Speed 3: 581
Pump Speed: 581

Output after fix:

./OpenCorsairLink.elf --device 0
Dev=0, CorsairLink Device Found: H110i Extreme!

Vendor: Corsair
Product: H110i Extreme
Firmware: 32.0.0.0
Temperature 0: 24.69
Temperature 1: 24.69
Temperature 2: 24.69
Fan Speed 0: 581
Fan Speed 1: 957
Pump Speed: 2373

### CODE REVIEW

**Comment by audiohacked** [comment]
Can you double check the fan port count?

**Comment by malakudi** [comment]
The H110i with device id 0x42 only supports two fans. You can see in above log that it repeats the data from fan0 when fan index > 2.

**Comment by audiohacked** [comment]
If the data was repeated, then pump speed would be 957 not 581.

**Comment by malakudi** [comment]
Maybe I didn't explain it correctly, fan index > 2 always shows data for inex 0. Following results were with the default settings of .fan_control_count = 4 and .pump_index = 5
Fan Speed 0: 581 <= index 0
Fan Speed 1: 957 <= index 1
Fan Speed 2: 2373 <= index 2 (real pump value)
Fan Speed 3: 581 <= index 3 (same as 0)
Pump Speed: 581 <= index 5 (same as 0)

**Pull request merged**
